### ISSUE TITLE
How to specify a namespace?

### ISSUE THREAD

**Issue by luisdavim** [bats-core/bats-detik#13]
Hi, I've been using `DETIK_CLIENT_NAME="kubectl -n my-namespace"` is there another way?

**Comment by vincent-zurczak** [comment]
Hi,

Actually, I used to put the namespace directly in my tests functions.
You could also use a variable, defined at the beginning of your scripts. Maybe we should create an additional variable in the library. But since it should be placed at the beginning of all your scripts, it is the same than defining the variable yourself.

**Comment by luisdavim** [comment]
Can you share an example of how you used to do it? I'm setting that variable multiple times in some test cases so I can switch between namespaces, maybe a dedicated variable would make it look cleaner.

**Comment by vincent-zurczak** [comment]
In my tests, work in different namespaces was spread over several files.
Not in a single file. So, you are right, we could have a variable we can change in the tests, just like `DEBUG_DETIK`. We do not want to modify the assertions syntax.

So, we could have...

```bash
# Set the working namespace
DETIK_NAMESPACE="ns1"

# Do some action in namespace "ns1"
...

# Assertion
run verify

# Change the working namespace
DETIK_NAMESPACE="ns2"
...

# To use the default client namespace
DETIK_NAMESPACE=""
```

**Comment by vincent-zurczak** [comment]
You can now use the `DETIK_CLIENT_NAMESPACE` variable to specify the namespace for assertions.
